import sys

ACTIVE = "ACTIVE"
RRC_CONFIGURED = "RRC_CONFIGURED"

MEASUREMENT_REPORT = "MEASUREMENT_REPORT"
HANDOVER_REQUEST = "HANDOVER_REQUEST"
HANDOVER_RESPONSE = "HANDOVER_RESPONSE"
RRC_RECONFIGURATION = "RRC_RECONFIGURATION"
RANDOM_ACCESS = "RANDOM_ACCESS"
RANDOM_ACCESS_RESPONSE = "RANDOM_ACCESS_RESPONSE"
RRC_RECONFIGURATION_COMPLETE = "RRC_RECONFIGURATION_COMPLETE"
HANDOVER_SUCCESS = "HANDOVER_SUCCESS"
SN_STATUS_TRANSFER = "SN_STATUS_TRANSFER"
HANDOVER_CANCEL = "HANDOVER_CANCEL"

NUMBER_CANDIDATE = 3
WINDOW_SIZE = 200
max_access_slots = WINDOW_SIZE
oracle_assignment = False
oracle_simulation = False

SOURCE_SUGGESTION_LONGEST = "SSU_LONGEST"
SOURCE_SUGGESTION_EARLIEST = "SSU_EARLIEST"
SOURCE_SUGGESTION_RANDOM = "SSU_RANDOM"
SOURCE_SUGGESTION_OUR = "SSU_OUR"

CANDIDATE_EARLIEST = "C_EARLIEST"
CANDIDATE_RANDOM = "C_RANDOM"
CANDIDATE_OUR = "C_OUR"

SOURCE_SELECTION_LONGEST = "SSE_LONGEST"
SOURCE_SELECTION_RANDOM = "SSE_RANDOM"

# sys.argv = ['notebook', SOURCE_SUGGESTION_LONGEST, CANDIDATE_RANDOM, CANDIDATE_OUR, '1'] # NOTE THIS WORK IN NOTEBOOK
# Modify this list if you have anything to compare
SOURCE_SUGGESTION_ALG = sys.argv[1]
CANDIDATE_ALG = sys.argv[2]
SOURCE_SELECTION_ALG = sys.argv[3]
max_access_opportunity = int(sys.argv[4])
RESULT_PATH = "./result/" + SOURCE_SUGGESTION_ALG + '|' + CANDIDATE_ALG + '|' + SOURCE_SELECTION_ALG + '|' + str(max_access_opportunity) + '.pkl'
